# Formula

price = m1 * area + m2 * bedrooms + m3 * age + b

# Importing libraries

In [102]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [9]:
# Data

In [35]:
home_price = {
    'area': [2600,3000,3200,3600,4000],
    'bedrooms': [3,4,None,3,5],
    'age': [20,15,18,30,8],
    'price': [550000,565000,610000,595000,760000]
}

In [37]:
df = pd.DataFrame(home_price, index=[x for x in range(len(home_price['area']))])
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

# Data cleaning

replace the NaN value by the median

In [44]:
median_bedroom = int(df.bedrooms.median())
median_bedroom

3

In [46]:
df.bedrooms = df.bedrooms.fillna(median_bedroom)

In [48]:
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

# Model creation

In [53]:
model = linear_model.LinearRegression()
model.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

# Model Parameters

In [59]:
model.coef_ # m1,m2,m3

array([   137.25, -26025.  ,  -6825.  ])

In [61]:
model.intercept_ # b

383724.9999999998

# Model Prediction

In [66]:
model.predict([[3000,3,40]]) # 3000sq ft, 3bedrooms, 40years old

C:\Users\syamp\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([444400.])

In [70]:
model.predict([[2500,3,5]])# 2500sq ft, 3bedrooms, 5year old

C:\Users\syamp\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([614650.])

# How it calculated

In [93]:
137.25*3000 + -26025*3 + -6825*40 + 383724.9999999998 # the first one

444399.9999999998