12 April 2025 4 PM

We are doing this method to avoid overfitting the data.

In this we'll randomly turn off (or) remove the neuron in the hidden layer at each iteration based on the given value like 0.5 -> 50% of neurons are turned off, etc.

Why will dropout help with overfitting?
1. It can't rely on one input as it might be dropped out at random
2. Neurons will not learn redundant details of inputs

In this, we are going to find whether it is rock or metal based on the sonar data

# Importing Library

In [30]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Reading Data

In [33]:
df = pd.read_csv("sonar_dataset.csv", header=None)
df.sample(5)

,0,1,2,3,4,5,6,7,8,9,...,51,52,53,54,55,56,57,58,59,60
10,0.0039,0.0063,0.0152,0.0336,0.0310,0.0284,0.0396,0.0272,0.0323,0.0452,...,0.0062,0.0120,0.0052,0.0056,0.0093,0.0042,0.0003,0.0053,0.0036,R
34,0.0311,0.0491,0.0692,0.0831,0.0079,0.0200,0.0981,0.1016,0.2025,0.0767,...,0.0087,0.0032,0.0130,0.0188,0.0101,0.0229,0.0182,0.0046,0.0038,R
130,0.0443,0.0446,0.0235,0.1008,0.2252,0.2611,0.2061,0.1668,0.1801,0.3083,...,0.0274,0.0205,0.0141,0.0185,0.0055,0.0045,0.0115,0.0152,0.0100,M
102,0.0587,0.1210,0.1268,0.1498,0.1436,0.0561,0.0832,0.0672,0.1372,0.2352,...,0.0331,0.0111,0.0088,0.0158,0.0122,0.0038,0.0101,0.0228,0.0124,M
123,0.0270,0.0163,0.0341,0.0247,0.0822,0.1256,0.1323,0.1584,0.2017,0.2122,...,0.0189,0.0204,0.0085,0.0043,0.0092,0.0138,0.0094,0.0105,0.0093,M

### Shape of data

In [36]:
df.shape

(208, 61)

### Check whether the data contains any NaN values

In [39]:
df.isna().sum() # since there is no NaN values, there is no need for data cleaning

0     0
1     0
2     0
3     0
4     0
     ..
56    0
57    0
58    0
59    0
60    0
Length: 61, dtype: int64

### Total Columns

In [42]:
df.columns # 60th is the output columns

Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60],
      dtype='int64')

### Different values in the output column

In [49]:
df[60].value_counts()

60
M    111
R     97
Name: count, dtype: int64

### Inputs and Outputs

In [56]:
x = df.drop(60,axis='columns')
y = df[60]
y.head() # it is in string, we have to convert it into numeric by one hot encoding

0    R
1    R
2    R
3    R
4    R
Name: 60, dtype: object

# One hot encoding

In [75]:
y = pd.get_dummies(y, drop_first = True) # since there are only two cols and after removing one, it knows the values are binary, so even mentionaning dtype = int, it will default to boolean only. To overcome this we have to chage datatype as int after it gives us boolean
y = y.astype(int)
y

     R
0    1
1    1
2    1
3    1
4    1
..  ..
203  0
204  0
205  0
206  0
207  0

[208 rows x 1 columns]

In [77]:
y.value_counts()

R
0    111
1     97
Name: count, dtype: int64

# Data Spliting

In [82]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=1)

In [86]:
x_train.shape

(166, 60)

In [90]:
x_test.shape

(42, 60)

# Model Creation & Training

In [93]:
import tensorflow as tf
from tensorflow import keras

In [107]:
model = keras.Sequential([
    keras.layers.Dense(60, input_dim=60, activation='relu'), # hidden layer
    keras.layers.Dense(30, activation='relu'), # hidden layer
    keras.layers.Dense(15, activation='relu'), # hidden layer
    keras.layers.Dense(1, activation='sigmoid') # output layer
])

model.compile(
    loss = 'binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

model.fit(x_train,y_train, batch_size=8, epochs=100) # mini-batch gradient descent. Each time the 8 batches runs and error and backpropogation occurs

Epoch 1/100
21/21 [==============================] - 1s 8ms/step - loss: 0.6857 - accuracy: 0.5361
Epoch 2/100
21/21 [==============================] - 0s 7ms/step - loss: 0.6662 - accuracy: 0.6386
Epoch 3/100
21/21 [==============================] - 0s 7ms/step - loss: 0.6487 - accuracy: 0.6627
Epoch 4/100
21/21 [==============================] - 0s 8ms/step - loss: 0.6296 - accuracy: 0.6807
Epoch 5/100
21/21 [==============================] - 0s 8ms/step - loss: 0.6049 - accuracy: 0.6747
Epoch 6/100
21/21 [==============================] - 0s 8ms/step - loss: 0.5713 - accuracy: 0.7169
Epoch 7/100
21/21 [==============================] - 0s 8ms/step - loss: 0.5386 - accuracy: 0.7470
Epoch 8/100
21/21 [==============================] - 0s 8ms/step - loss: 0.5001 - accuracy: 0.7470
Epoch 9/100
21/21 [==============================] - 0s 8ms/step - loss: 0.4434 - accuracy: 0.8072
Epoch 10/100
21/21 [==============================] - 0s 8ms/step - loss: 0.4174 - accuracy: 0.8133
Epoch 11/100
21/21 [==============================] - 0s 8ms/step - loss: 0.3845 - accuracy: 0.8795
Epoch 12/100
21/21 [==============================] - 0s 8ms/step - loss: 0.3882 - accuracy: 0.8373
Epoch 13/100
21/21 [==============================] - 0s 8ms/step - loss: 0.3554 - accuracy: 0.8494
Epoch 14/100
21/21 [==============================] - 0s 7ms/step - loss: 0.3655 - accuracy: 0.8373
Epoch 15/100
21/21 [==============================] - 0s 7ms/step - loss: 0.3352 - accuracy: 0.8614
Epoch 16/100
21/21 [==============================] - 0s 8ms/step - loss: 0.2990 - accuracy: 0.9157
Epoch 17/100
21/21 [==============================] - 0s 8ms/step - loss: 0.2844 - accuracy: 0.9096
Epoch 18/100
21/21 [==============================] - 0s 7ms/step - loss: 0.2823 - accuracy: 0.8675
Epoch 19/100
21/21 [==============================] - 0s 9ms/step - loss: 0.3180 - accuracy: 0.8614
Epoch 20/100
21/21 [==============================] - 0s 7ms/step - loss: 0.2559 - accuracy: 0.9036
Epoch 21/100
21/21 [==============================] - 0s 8ms/step - loss: 0.2465 - accuracy: 0.9277
Epoch 22/100
21/21 [==============================] - 0s 7ms/step - loss: 0.2217 - accuracy: 0.9277
Epoch 23/100
21/21 [==============================] - 0s 7ms/step - loss: 0.2163 - accuracy: 0.9277
Epoch 24/100
21/21 [==============================] - 0s 7ms/step - loss: 0.2312 - accuracy: 0.9096
Epoch 25/100
21/21 [==============================] - 0s 8ms/step - loss: 0.2153 - accuracy: 0.9036
Epoch 26/100
21/21 [==============================] - 0s 7ms/step - loss: 0.1883 - accuracy: 0.9578
Epoch 27/100
21/21 [==============================] - 0s 7ms/step - loss: 0.1975 - accuracy: 0.9217
Epoch 28/100
21/21 [==============================] - 0s 7ms/step - loss: 0.1987 - accuracy: 0.9096
Epoch 29/100
21/21 [==============================] - 0s 7ms/step - loss: 0.1964 - accuracy: 0.9217
Epoch 30/100
21/21 [==============================] - 0s 7ms/step - loss: 0.1867 - accuracy: 0.8855
Epoch 31/100
21/21 [==============================] - 0s 7ms/step - loss: 0.2157 - accuracy: 0.9157
Epoch 32/100
21/21 [==============================] - 0s 7ms/step - loss: 0.1590 - accuracy: 0.9458
Epoch 33/100
21/21 [==============================] - 0s 7ms/step - loss: 0.1263 - accuracy: 0.9699
Epoch 34/100
21/21 [==============================] - 0s 7ms/step - loss: 0.1183 - accuracy: 0.9639
Epoch 35/100
21/21 [==============================] - 0s 7ms/step - loss: 0.1120 - accuracy: 0.9699
Epoch 36/100
21/21 [==============================] - 0s 7ms/step - loss: 0.1206 - accuracy: 0.9518
Epoch 37/100
21/21 [==============================] - 0s 8ms/step - loss: 0.0991 - accuracy: 0.9819
Epoch 38/100
21/21 [==============================] - 0s 8ms/step - loss: 0.1377 - accuracy: 0.9518
Epoch 39/100
21/21 [==============================] - 0s 8ms/step - loss: 0.0973 - accuracy: 0.9699
Epoch 40/100
21/21 [==============================] - 0s 7ms/step - loss: 0.0868 - accuracy: 0.9819
Epoch 41/100
21/21 [==============================] - 0s 7ms/step - loss: 0.0753 - accuracy: 0.9819
Epoch 42/100
21/21 [==============================] - 0s 7ms/step - loss: 0.0626 - accuracy: 0.9940
Epoch 43/100
21/21 [==============================] - 0s 7ms/step - loss: 0.0681 - accuracy: 0.9880
Epoch 44/100
21/21 [==============================] - 0s 7ms/step - loss: 0.0627 - accuracy: 1.0000
Epoch 45/100
21/21 [==============================] - 0s 7ms/step - loss: 0.0592 - accuracy: 0.9880
Epoch 46/100
21/21 [==============================] - 0s 7ms/step - loss: 0.0459 - accuracy: 0.9940
Epoch 47/100
21/21 [==============================] - 0s 8ms/step - loss: 0.0436 - accuracy: 0.9940
Epoch 48/100
21/21 [==============================] - 0s 7ms/step - loss: 0.0411 - accuracy: 0.9940
Epoch 49/100
21/21 [==============================] - 0s 7ms/step - loss: 0.0361 - accuracy: 0.9940
Epoch 50/100
21/21 [==============================] - 0s 7ms/step - loss: 0.0364 - accuracy: 0.9940
Epoch 51/100
21/21 [==============================] - 0s 7ms/step - loss: 0.0460 - accuracy: 0.9940
Epoch 52/100
21/21 [==============================] - 0s 7ms/step - loss: 0.0542 - accuracy: 0.9819
Epoch 53/100
21/21 [==============================] - 0s 7ms/step - loss: 0.0501 - accuracy: 0.9940
Epoch 54/100
21/21 [==============================] - 0s 7ms/step - loss: 0.0314 - accuracy: 1.0000
Epoch 55/100
21/21 [==============================] - 0s 7ms/step - loss: 0.0381 - accuracy: 0.9940
Epoch 56/100
21/21 [==============================] - 0s 7ms/step - loss: 0.0412 - accuracy: 0.9940
Epoch 57/100
21/21 [==============================] - 0s 7ms/step - loss: 0.0385 - accuracy: 0.9940
Epoch 58/100
21/21 [==============================] - 0s 8ms/step - loss: 0.0265 - accuracy: 0.9940
Epoch 59/100
21/21 [==============================] - 0s 8ms/step - loss: 0.0229 - accuracy: 0.9940
Epoch 60/100
21/21 [==============================] - 0s 7ms/step - loss: 0.0173 - accuracy: 1.0000
Epoch 61/100
21/21 [==============================] - 0s 7ms/step - loss: 0.0165 - accuracy: 1.0000
Epoch 62/100
21/21 [==============================] - 0s 7ms/step - loss: 0.0181 - accuracy: 1.0000
Epoch 63/100
21/21 [==============================] - 0s 7ms/step - loss: 0.0150 - accuracy: 1.0000
Epoch 64/100
21/21 [==============================] - 0s 7ms/step - loss: 0.0171 - accuracy: 1.0000
Epoch 65/100
21/21 [==============================] - 0s 7ms/step - loss: 0.0174 - accuracy: 1.0000
Epoch 66/100
21/21 [==============================] - 0s 7ms/step - loss: 0.0121 - accuracy: 1.0000
Epoch 67/100
21/21 [==============================] - 0s 7ms/step - loss: 0.0124 - accuracy: 1.0000
Epoch 68/100
21/21 [==============================] - 0s 7ms/step - loss: 0.0128 - accuracy: 1.0000
Epoch 69/100
21/21 [==============================] - 0s 8ms/step - loss: 0.0101 - accuracy: 1.0000
Epoch 70/100
21/21 [==============================] - 0s 7ms/step - loss: 0.0098 - accuracy: 1.0000
Epoch 71/100
21/21 [==============================] - 0s 8ms/step - loss: 0.0094 - accuracy: 1.0000
Epoch 72/100
21/21 [==============================] - 0s 7ms/step - loss: 0.0087 - accuracy: 1.0000
Epoch 73/100
21/21 [==============================] - 0s 8ms/step - loss: 0.0079 - accuracy: 1.0000
Epoch 74/100
21/21 [==============================] - 0s 7ms/step - loss: 0.0070 - accuracy: 1.0000
Epoch 75/100
21/21 [==============================] - 0s 8ms/step - loss: 0.0077 - accuracy: 1.0000
Epoch 76/100
21/21 [==============================] - 0s 7ms/step - loss: 0.0070 - accuracy: 1.0000
Epoch 77/100
21/21 [==============================] - 0s 7ms/step - loss: 0.0063 - accuracy: 1.0000
Epoch 78/100
21/21 [==============================] - 0s 8ms/step - loss: 0.0062 - accuracy: 1.0000
Epoch 79/100
21/21 [==============================] - 0s 8ms/step - loss: 0.0060 - accuracy: 1.0000
Epoch 80/100
21/21 [==============================] - 0s 8ms/step - loss: 0.0063 - accuracy: 1.0000
Epoch 81/100
21/21 [==============================] - 0s 7ms/step - loss: 0.0065 - accuracy: 1.0000
Epoch 82/100
21/21 [==============================] - 0s 8ms/step - loss: 0.0082 - accuracy: 1.0000
Epoch 83/100
21/21 [==============================] - 0s 7ms/step - loss: 0.0064 - accuracy: 1.0000
Epoch 84/100
21/21 [==============================] - 0s 7ms/step - loss: 0.0049 - accuracy: 1.0000
Epoch 85/100
21/21 [==============================] - 0s 7ms/step - loss: 0.0045 - accuracy: 1.0000
Epoch 86/100
21/21 [==============================] - 0s 7ms/step - loss: 0.0042 - accuracy: 1.0000
Epoch 87/100
21/21 [==============================] - 0s 8ms/step - loss: 0.0041 - accuracy: 1.0000
Epoch 88/100
21/21 [==============================] - 0s 7ms/step - loss: 0.0038 - accuracy: 1.0000
Epoch 89/100
21/21 [==============================] - 0s 8ms/step - loss: 0.0038 - accuracy: 1.0000
Epoch 90/100
21/21 [==============================] - 0s 6ms/step - loss: 0.0034 - accuracy: 1.0000
Epoch 91/100
21/21 [==============================] - 0s 7ms/step - loss: 0.0035 - accuracy: 1.0000
Epoch 92/100
21/21 [==============================] - 0s 7ms/step - loss: 0.0034 - accuracy: 1.0000
Epoch 93/100
21/21 [==============================] - 0s 7ms/step - loss: 0.0033 - accuracy: 1.0000
Epoch 94/100
21/21 [==============================] - 0s 7ms/step - loss: 0.0031 - accuracy: 1.0000
Epoch 95/100
21/21 [==============================] - 0s 7ms/step - loss: 0.0029 - accuracy: 1.0000
Epoch 96/100
21/21 [==============================] - 0s 8ms/step - loss: 0.0028 - accuracy: 1.0000
Epoch 97/100
21/21 [==============================] - 0s 7ms/step - loss: 0.0027 - accuracy: 1.0000
Epoch 98/100
21/21 [==============================] - 0s 7ms/step - loss: 0.0029 - accuracy: 1.0000
Epoch 99/100
21/21 [==============================] - 0s 7ms/step - loss: 0.0029 - accuracy: 1.0000
Epoch 100/100
21/21 [==============================] - 0s 7ms/step - loss: 0.0027 - accuracy: 1.0000

Accuracy = 100 -> overfitting

# Model Evaluation

In [110]:
model.evaluate(x_test,y_test)

2/2 [==============================] - 0s 7ms/step - loss: 1.2500 - accuracy: 0.7143

[1.2499749660491943, 0.7142857313156128]

Test accuracy -> 71% (due to overfitting)

# Model Prediction

In [123]:
y_pred = model.predict(x_test).reshape(-1)
print(y_pred[:10])

# round the values to nearest integer i.e 0 0r 1
y_pred = np.round(y_pred)
print(y_pred[:10])

2/2 [==============================] - 0s 5ms/step
[4.7659529e-07 9.9948871e-01 9.9989438e-01 4.1409334e-05 9.9999988e-01
 9.9745625e-01 4.8590813e-02 1.0000000e+00 9.5269905e-05 1.0000000e+00]
[0. 1. 1. 0. 1. 1. 0. 1. 0. 1.]

In [131]:
y_test[:10]

     R
186  0
155  0
165  0
200  0
58   1
34   1
151  0
18   1
202  0
62   1

# Classification report

In [134]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.67      0.80      0.73        20
           1       0.78      0.64      0.70        22

    accuracy                           0.71        42
   macro avg       0.72      0.72      0.71        42
weighted avg       0.72      0.71      0.71        42

# Adding Droupout layer

Dropout layer can be added after every hidden layer

In [161]:
modeld = keras.Sequential([
    keras.layers.Dense(60, input_dim=60, activation='relu'), # hidden layer
    keras.layers.Dropout(0.5), # Dropout layer - 50%
    keras.layers.Dense(30, activation='relu'), # hidden layer
    keras.layers.Dropout(0.5), # Dropout layer - 50%
    keras.layers.Dense(15, activation='relu'), # hidden layer
    keras.layers.Dropout(0.5), # Dropout layer - 50%
    keras.layers.Dense(1, activation='sigmoid') # output layer
])

modeld.compile(
    loss = 'binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

modeld.fit(x_train,y_train, batch_size=8, epochs=100) # mini-batch gradient descent. Each time the 8 batches runs and error and backpropogation occurs

Epoch 1/100
21/21 [==============================] - 1s 4ms/step - loss: 0.7667 - accuracy: 0.4337
Epoch 2/100
21/21 [==============================] - 0s 4ms/step - loss: 0.7223 - accuracy: 0.5120
Epoch 3/100
21/21 [==============================] - 0s 4ms/step - loss: 0.7100 - accuracy: 0.5301
Epoch 4/100
21/21 [==============================] - 0s 4ms/step - loss: 0.7049 - accuracy: 0.5000
Epoch 5/100
21/21 [==============================] - 0s 5ms/step - loss: 0.6731 - accuracy: 0.5783
Epoch 6/100
21/21 [==============================] - 0s 5ms/step - loss: 0.6625 - accuracy: 0.5964
Epoch 7/100
21/21 [==============================] - 0s 4ms/step - loss: 0.6999 - accuracy: 0.5482
Epoch 8/100
21/21 [==============================] - 0s 4ms/step - loss: 0.6902 - accuracy: 0.5843
Epoch 9/100
21/21 [==============================] - 0s 4ms/step - loss: 0.6807 - accuracy: 0.5964
Epoch 10/100
21/21 [==============================] - 0s 4ms/step - loss: 0.6677 - accuracy: 0.5723
Epoch 11/100
21/21 [==============================] - 0s 5ms/step - loss: 0.6974 - accuracy: 0.5542
Epoch 12/100
21/21 [==============================] - 0s 5ms/step - loss: 0.6801 - accuracy: 0.5783
Epoch 13/100
21/21 [==============================] - 0s 5ms/step - loss: 0.6853 - accuracy: 0.5723
Epoch 14/100
21/21 [==============================] - 0s 4ms/step - loss: 0.7054 - accuracy: 0.5241
Epoch 15/100
21/21 [==============================] - 0s 4ms/step - loss: 0.6951 - accuracy: 0.5301
Epoch 16/100
21/21 [==============================] - 0s 4ms/step - loss: 0.6799 - accuracy: 0.5181
Epoch 17/100
21/21 [==============================] - 0s 5ms/step - loss: 0.6850 - accuracy: 0.5663
Epoch 18/100
21/21 [==============================] - 0s 4ms/step - loss: 0.6663 - accuracy: 0.5602
Epoch 19/100
21/21 [==============================] - 0s 4ms/step - loss: 0.6827 - accuracy: 0.5663
Epoch 20/100
21/21 [==============================] - 0s 5ms/step - loss: 0.6803 - accuracy: 0.5723
Epoch 21/100
21/21 [==============================] - 0s 5ms/step - loss: 0.6792 - accuracy: 0.5964
Epoch 22/100
21/21 [==============================] - 0s 4ms/step - loss: 0.6614 - accuracy: 0.6145
Epoch 23/100
21/21 [==============================] - 0s 4ms/step - loss: 0.6361 - accuracy: 0.6145
Epoch 24/100
21/21 [==============================] - 0s 5ms/step - loss: 0.6523 - accuracy: 0.5602
Epoch 25/100
21/21 [==============================] - 0s 5ms/step - loss: 0.6033 - accuracy: 0.6446
Epoch 26/100
21/21 [==============================] - 0s 5ms/step - loss: 0.6429 - accuracy: 0.6145
Epoch 27/100
21/21 [==============================] - 0s 5ms/step - loss: 0.6354 - accuracy: 0.6265
Epoch 28/100
21/21 [==============================] - 0s 4ms/step - loss: 0.6561 - accuracy: 0.6024
Epoch 29/100
21/21 [==============================] - 0s 4ms/step - loss: 0.6369 - accuracy: 0.5843
Epoch 30/100
21/21 [==============================] - 0s 4ms/step - loss: 0.6336 - accuracy: 0.6024
Epoch 31/100
21/21 [==============================] - 0s 4ms/step - loss: 0.6162 - accuracy: 0.6446
Epoch 32/100
21/21 [==============================] - 0s 4ms/step - loss: 0.6161 - accuracy: 0.6687
Epoch 33/100
21/21 [==============================] - 0s 4ms/step - loss: 0.6107 - accuracy: 0.6566
Epoch 34/100
21/21 [==============================] - 0s 5ms/step - loss: 0.5989 - accuracy: 0.6747
Epoch 35/100
21/21 [==============================] - 0s 4ms/step - loss: 0.5749 - accuracy: 0.6807
Epoch 36/100
21/21 [==============================] - 0s 4ms/step - loss: 0.6110 - accuracy: 0.6627
Epoch 37/100
21/21 [==============================] - 0s 4ms/step - loss: 0.6103 - accuracy: 0.6627
Epoch 38/100
21/21 [==============================] - 0s 4ms/step - loss: 0.5671 - accuracy: 0.6867
Epoch 39/100
21/21 [==============================] - 0s 4ms/step - loss: 0.5705 - accuracy: 0.7289
Epoch 40/100
21/21 [==============================] - 0s 4ms/step - loss: 0.5508 - accuracy: 0.7349
Epoch 41/100
21/21 [==============================] - 0s 4ms/step - loss: 0.5608 - accuracy: 0.7470
Epoch 42/100
21/21 [==============================] - 0s 4ms/step - loss: 0.5290 - accuracy: 0.7410
Epoch 43/100
21/21 [==============================] - 0s 4ms/step - loss: 0.5405 - accuracy: 0.7410
Epoch 44/100
21/21 [==============================] - 0s 5ms/step - loss: 0.5262 - accuracy: 0.7410
Epoch 45/100
21/21 [==============================] - 0s 4ms/step - loss: 0.5493 - accuracy: 0.7229
Epoch 46/100
21/21 [==============================] - 0s 4ms/step - loss: 0.5423 - accuracy: 0.7108
Epoch 47/100
21/21 [==============================] - 0s 4ms/step - loss: 0.4973 - accuracy: 0.7711
Epoch 48/100
21/21 [==============================] - 0s 4ms/step - loss: 0.4775 - accuracy: 0.7771
Epoch 49/100
21/21 [==============================] - 0s 4ms/step - loss: 0.5170 - accuracy: 0.7410
Epoch 50/100
21/21 [==============================] - 0s 4ms/step - loss: 0.5249 - accuracy: 0.7410
Epoch 51/100
21/21 [==============================] - 0s 4ms/step - loss: 0.5060 - accuracy: 0.7530
Epoch 52/100
21/21 [==============================] - 0s 4ms/step - loss: 0.4681 - accuracy: 0.7831
Epoch 53/100
21/21 [==============================] - 0s 4ms/step - loss: 0.5347 - accuracy: 0.7651
Epoch 54/100
21/21 [==============================] - 0s 5ms/step - loss: 0.5271 - accuracy: 0.8012
Epoch 55/100
21/21 [==============================] - 0s 4ms/step - loss: 0.4832 - accuracy: 0.7590
Epoch 56/100
21/21 [==============================] - 0s 4ms/step - loss: 0.4239 - accuracy: 0.8313
Epoch 57/100
21/21 [==============================] - 0s 5ms/step - loss: 0.4317 - accuracy: 0.8012
Epoch 58/100
21/21 [==============================] - 0s 5ms/step - loss: 0.4624 - accuracy: 0.8012
Epoch 59/100
21/21 [==============================] - 0s 5ms/step - loss: 0.4378 - accuracy: 0.7952
Epoch 60/100
21/21 [==============================] - 0s 4ms/step - loss: 0.4067 - accuracy: 0.8193
Epoch 61/100
21/21 [==============================] - 0s 4ms/step - loss: 0.4608 - accuracy: 0.7651
Epoch 62/100
21/21 [==============================] - 0s 5ms/step - loss: 0.4491 - accuracy: 0.7771
Epoch 63/100
21/21 [==============================] - 0s 5ms/step - loss: 0.3971 - accuracy: 0.8614
Epoch 64/100
21/21 [==============================] - 0s 5ms/step - loss: 0.3893 - accuracy: 0.8012
Epoch 65/100
21/21 [==============================] - 0s 4ms/step - loss: 0.4937 - accuracy: 0.7952
Epoch 66/100
21/21 [==============================] - 0s 5ms/step - loss: 0.4143 - accuracy: 0.8133
Epoch 67/100
21/21 [==============================] - 0s 4ms/step - loss: 0.4044 - accuracy: 0.8434
Epoch 68/100
21/21 [==============================] - 0s 4ms/step - loss: 0.4641 - accuracy: 0.7410
Epoch 69/100
21/21 [==============================] - 0s 5ms/step - loss: 0.3895 - accuracy: 0.8434
Epoch 70/100
21/21 [==============================] - 0s 4ms/step - loss: 0.3495 - accuracy: 0.8675
Epoch 71/100
21/21 [==============================] - 0s 5ms/step - loss: 0.3735 - accuracy: 0.8193
Epoch 72/100
21/21 [==============================] - 0s 6ms/step - loss: 0.4538 - accuracy: 0.8193
Epoch 73/100
21/21 [==============================] - 0s 5ms/step - loss: 0.4007 - accuracy: 0.8614
Epoch 74/100
21/21 [==============================] - 0s 5ms/step - loss: 0.3875 - accuracy: 0.8373
Epoch 75/100
21/21 [==============================] - 0s 4ms/step - loss: 0.3804 - accuracy: 0.8916
Epoch 76/100
21/21 [==============================] - 0s 4ms/step - loss: 0.3634 - accuracy: 0.8675
Epoch 77/100
21/21 [==============================] - 0s 5ms/step - loss: 0.3397 - accuracy: 0.8614
Epoch 78/100
21/21 [==============================] - 0s 5ms/step - loss: 0.3418 - accuracy: 0.8373
Epoch 79/100
21/21 [==============================] - 0s 4ms/step - loss: 0.3981 - accuracy: 0.8193
Epoch 80/100
21/21 [==============================] - 0s 5ms/step - loss: 0.2771 - accuracy: 0.9337
Epoch 81/100
21/21 [==============================] - 0s 5ms/step - loss: 0.3435 - accuracy: 0.8675
Epoch 82/100
21/21 [==============================] - 0s 5ms/step - loss: 0.3584 - accuracy: 0.8554
Epoch 83/100
21/21 [==============================] - 0s 5ms/step - loss: 0.3147 - accuracy: 0.8735
Epoch 84/100
21/21 [==============================] - 0s 5ms/step - loss: 0.3417 - accuracy: 0.8554
Epoch 85/100
21/21 [==============================] - 0s 5ms/step - loss: 0.3187 - accuracy: 0.8675
Epoch 86/100
21/21 [==============================] - 0s 5ms/step - loss: 0.4003 - accuracy: 0.8434
Epoch 87/100
21/21 [==============================] - 0s 4ms/step - loss: 0.2890 - accuracy: 0.9036
Epoch 88/100
21/21 [==============================] - 0s 5ms/step - loss: 0.2851 - accuracy: 0.8795
Epoch 89/100
21/21 [==============================] - 0s 5ms/step - loss: 0.2621 - accuracy: 0.9096
Epoch 90/100
21/21 [==============================] - 0s 5ms/step - loss: 0.2540 - accuracy: 0.9036
Epoch 91/100
21/21 [==============================] - 0s 5ms/step - loss: 0.3432 - accuracy: 0.8494
Epoch 92/100
21/21 [==============================] - 0s 5ms/step - loss: 0.2525 - accuracy: 0.9277
Epoch 93/100
21/21 [==============================] - 0s 5ms/step - loss: 0.3089 - accuracy: 0.8494
Epoch 94/100
21/21 [==============================] - 0s 5ms/step - loss: 0.2691 - accuracy: 0.9217
Epoch 95/100
21/21 [==============================] - 0s 5ms/step - loss: 0.2514 - accuracy: 0.9036
Epoch 96/100
21/21 [==============================] - 0s 5ms/step - loss: 0.2548 - accuracy: 0.9036
Epoch 97/100
21/21 [==============================] - 0s 5ms/step - loss: 0.2985 - accuracy: 0.8916
Epoch 98/100
21/21 [==============================] - 0s 5ms/step - loss: 0.3138 - accuracy: 0.8494
Epoch 99/100
21/21 [==============================] - 0s 5ms/step - loss: 0.3006 - accuracy: 0.8855
Epoch 100/100
21/21 [==============================] - 0s 5ms/step - loss: 0.2435 - accuracy: 0.9096

Now Training accuracy reduced means No overfitting

# Model Evaluation after Dropout layer

In [165]:
modeld.evaluate(x_test, y_test)

WARNING:tensorflow:5 out of the last 9 calls to <function Model.make_test_function.<locals>.test_function at 0x00000225F6414A60> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
2/2 [==============================] - 0s 4ms/step - loss: 0.4926 - accuracy: 0.8095

[0.4926258325576782, 0.8095238208770752]

Test accuracy increased

# Model Prediction

In [174]:
y_pred = model.predict(x_test).reshape(-1)

# round the values to nearest integer i.e 0 0r 1
y_pred = np.round(y_pred)
print(y_pred[:10])

2/2 [==============================] - 0s 3ms/step
[0. 1. 1. 0. 1. 1. 0. 1. 0. 1.]

# Classification report after Dropout layer

In [177]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.76      0.80      0.78        20
           1       0.81      0.77      0.79        22

    accuracy                           0.79        42
   macro avg       0.79      0.79      0.79        42
weighted avg       0.79      0.79      0.79        42